AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'app/helpers/application_helper.rb'
    - 'lib/configuration_reader.rb'

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 18

Metrics/MethodLength:   
  Max: 20

Documentation: 
  Enabled: false
