AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'test/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 150

Documentation: 
  Enabled: false
