version: '3.5'

services:
  postgres:
    environment:
      - POSTGRES_DB=finepanel_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build:
      dockerfile: Dockerfile.prod
      labels:
        - "com.mooveit.description=Finepanel"
        - "com.mooveit.department=mooveit"
        - "com.mooveit.environment=prod"
    restart: always
    command: bash -c "bundle exec puma"
    ports:
      - 80:3000
    volumes:
      - $PWD/app/tmp/feed_files:/usr/src/app/tmp/feed_files
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  sidekiq:
    build:
      dockerfile: Dockerfile.prod
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      - SIDEKIQ_CONCURRENCY=5
    volumes:
      - $PWD/app/tmp/feed_files:/usr/src/app/tmp/feed_files
    logging:
      options:
        max-size: "10m"
        max-file: "5"
