version: '3.5'

services:

  app:
    build:
      dockerfile: Dockerfile.dev
      labels:
        - "com.mooveit.description=Finepanel"
        - "com.mooveit.department=mooveit"
        - "com.mooveit.environment=dev"
        - "com.mooveit.label-with-empty-value"
    command: bash -c "bundle exec puma"
    ports:
      - 3000:3000
  sidekiq:
    build:
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
