version: '3.5'

services:

  postgres:
    image: postgres:10
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=finepanel_dev
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432

  app:
    build:
      context: app
    image: finepanel:latest
    volumes:
      - $PWD/app:/usr/src/app
    depends_on:
      - postgres
