version: '3.5'

services:
  postgres:
    environment:
      - POSTGRES_DB=finepanel_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build:
      dockerfile: Dockerfile.dev
      labels:
        - "com.mooveit.description=Finepanel"
        - "com.mooveit.department=mooveit"
        - "com.mooveit.environment=dev"
    command: bash -c "bundle exec puma"
    ports:
      - 3000:3000
  sidekiq:
    build:
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      - SIDEKIQ_CONCURRENCY=2
