version: '3.5'

services:
  postgres:
    environment:
      - POSTGRES_DB=finepanel_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build:
      dockerfile: Dockerfile.prod
      labels:
        - "com.mooveit.description=Finepanel"
        - "com.mooveit.department=mooveit"
        - "com.mooveit.environment=prod"
    restart: always
    command: bash -c "bundle exec puma"
    expose:
      - 80
    volumes:
      - $PWD/app/tmp:/usr/src/app/tmp
      - $PWD/log/app:/usr/src/app/log

  sidekiq:
    build:
      dockerfile: Dockerfile.prod
    command: bundle exec sidekiq -C config/sidekiq.yml | tee ./log/sidekiq.log
    environment:
      - SIDEKIQ_CONCURRENCY=5
    volumes:
      # - $PWD/app/tmp/feed_files:/usr/src/app/tmp/feed_files
      - $PWD/log/app:/usr/src/app/log
      - $PWD/app/tmp:/usr/src/app/tmp

  nginx:
    image: nginx:latest
    volumes:
      - $PWD/conf/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/log/nginx:/var/log/nginx
    restart: always
    ports:
      - 80:3000
    depends_on:
      - app
