FROM ruby:2.5.1-alpine

LABEL maintainer="sre@moove-it.com"
LABEL version="1.0.0"

##########################
# Arguments              #
##########################

ARG AUTOMATICALLY_MIGRATE=true

ENV AUTOMATICALLY_MIGRATE=$AUTOMATICALLY_MIGRATE

##########################
# Install software       #
##########################

# Install base packages and other software
RUN apk add --no-cache nodejs build-base postgresql-dev libxml2-dev libxslt-dev sqlite-dev tzdata \
  git openssh postgresql

##########################
# Set working directory  #
##########################

# Set working directory this directoy is going to
# be used by default
WORKDIR /app

##########################
# Add manifest files     #
##########################

# Copy metadata files that are used to install
# dependencies
COPY Gemfile Gemfile.lock ./

##########################
# Configure dependencies #
##########################

# Set the place where bundle is going to install gems
ENV BUNDLE_PATH /bundle

# Configure bundle to to build nokogiri using system libraries
RUN bundle config --global build.nokogiri --use-system-libraries && \
  bundle config git.allow_insecure true

##########################
# Run the app            #
##########################

ENTRYPOINT ["/app/entrypoint.local.sh"]

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
