FROM ruby:2.5.1-alpine

##########################
# Arguments              #
##########################

ARG AUTOMATICALLY_MIGRATE=true

ENV AUTOMATICALLY_MIGRATE=$AUTOMATICALLY_MIGRATE

##########################
# Install software       #
##########################

# Install base packages and other software
RUN apk add --no-cache jq nodejs build-base postgresql-dev libxml2-dev libxslt-dev sqlite-dev tzdata \
  git openssh postgresql

##########################
# Set working directory  #
##########################

# Set working directory this directoy is going to
# be used by default
WORKDIR /app

##########################
# Add manifest files     #
##########################

# Copy metadata files that are used to install
# dependencies
COPY Gemfile Gemfile.lock ./

##########################
# Configure dependencies #
##########################

# Set the place where bundle is going to install gems
ENV BUNDLE_PATH /bundle

# Configure bundle to to build nokogiri using system libraries
RUN bundle config --global build.nokogiri --use-system-libraries

##########################
# App Instalation        #
##########################

COPY . /app

ENV RAILS_ENV production

RUN bundle install --jobs `expr $(cat /proc/cpuinfo | grep -c "cpu cores") - 1` --retry 3 && \
  bundle exec rake assets:precompile

##########################
# Run the app            #
##########################

ENTRYPOINT ["/app/entrypoint.release.sh"]

# --- SSL.com root CA fix (required after cert renewal) ---
RUN apk add --no-cache ca-certificates openssl \
 && mkdir -p /usr/local/share/ca-certificates

COPY sslcom-root-ca-rsa.crt /usr/local/share/ca-certificates/sslcom-root-ca-rsa.crt

RUN update-ca-certificates

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
# --- end SSL.com fix ---




CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
