user_profile_path: 'https://survey.finepanel.net//wix/p785267057.aspx?exit=controlportal'
project_id: 'p785267057'
sender_email: 'mailer@us.confirmit.com'
sender_email_alternative: 'panel@fine-research.com'
status_new_survey: '0'
status_initiated_survey: '66'
admin_user_emails: ['dcasar@fine-research.com']
