user_profile_path: 'https://survey.finepanel.net//wix/p785267057.aspx?exit=controlportal'
project_id: 'p785267057'
sender_email: 'mailer@us.confirmit.com'
sender_email_alternative: 'panel@fine-research.com'
status_new_survey: '0'
status_initiated_survey: '66'
status_dynamed_enabled: '1'
admin_user_emails: ['dcasar@fine-research.com']

aacd_profile_path: 'https://survey.finepanel.net//wix/p785267057.aspx?exit=controlportal&r=114170&s=YLLAYBFI'
icw_profile_path: 'https://survey.finepanel.net//wix/p785267057.aspx?exit=controlportal&r=201316&s=IYRKPEEP'
stc_mx_profile_path: 'https://survey.finepanel.net//wix/p785267057.aspx?exit=controlportal&r=119287&s=OPVSITAQ'
stc_co_profile_path: 'https://survey.finepanel.net//wix/p785267057.aspx?exit=controlportal&r=776431&s=YUGFWLST'

dynamed_subdomain: 'https://dynamed.finepanel.net'
