common: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  port: 5433
  password:

development:
  <<: *default
  database: finepanel_dev

test:
  <<: *default
  database: finepanel_test
