default: &default
  adapter: postgresql
  database: <%= ENV["DATABASE_NAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  username: <%= ENV["DATABASE_USER"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  pool: <%= ENV["DB_POOL"] %>

development:
  <<: *default
  min_messages: WARNING

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
